name: 'Playwright report comment'
description: 'Report Playwright test results as pull request comments'
author: 'Philipp Daun <daun@daun.ltd>'
branding:
  icon: 'message-circle'
  color: 'purple'
inputs:
  github-token:
    description: 'The GitHub access token'
    required: false
    default: ${{ github.token }}
  report-file:
    description: 'Path to the generated json report file, if differing from the default'
    required: false
    default: 'results.json'
  comment-title:
    description: 'Customize the title of the pull request comment'
    required: false
    default: 'Playwright test results'
  icon-style:
    description: 'The icons to use: octicons or emoji'
    required: false
    default: 'octicons'
outputs:
  comment-id:
    description: 'The ID of the comment that was created or updated'

runs:
  using: node16
  main: index.js
