name: Manual Tests

on:
  issue_comment:
    types: [created]

jobs:
  test:
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/playwright') }}
    name: Run playwright tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        ref: refs/pull/${{ github.event.issue.number }}/head

    - name: Set up node
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install browsers
      run: npx playwright install --with-deps

    - name: Run tests
      run: PLAYWRIGHT_JSON_OUTPUT_NAME=results.json npx playwright test --config ./tests/config/playwright.config.ts

    - name: Create report comment
      uses: ./.github/actions/playwright-report-summary
      if: always()
      with:
        report-file: results.json
