name: Tests

on:
  push:
    branches: [ main, master, next ]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Bundle library
      run: npm run build
    - name: Install browsers
      run: npm run test:install
    - name: Run tests
      run: npm run test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: tests/reports/
        retention-days: 14
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-results
        path: tests/results/
        retention-days: 14
